src/Entity/DndEquipment.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DndEquipmentRepository")
 */
class DndEquipment
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\DndEquipmentType", inversedBy="equipments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\DndEquipmentSubtype", inversedBy="equipments")
     */
    private $subtype;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $cost;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $weight;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $properties;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $damage;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $damage_type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $armor_class;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $strength;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $stealth;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCost(): ?int
    {
        return $this->cost;
    }

    public function setCost(?int $cost): self
    {
        $this->cost = $cost;

        return $this;
    }

    public function getWeight(): ?float
    {
        return $this->weight;
    }

    public function setWeight(?float $weight): self
    {
        $this->weight = $weight;

        return $this;
    }

    public function getInfo(): ?string
    {
        return $this->info;
    }

    public function setInfo(?string $info): self
    {
        $this->info = $info;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getDamage(): ?string
    {
        return $this->damage;
    }

    public function setDamage(?string $damage): self
    {
        $this->damage = $damage;

        return $this;
    }

    public function getDamageType(): ?string
    {
        return $this->damage_type;
    }

    public function setDamageType(?string $damage_type): self
    {
        $this->damage_type = $damage_type;

        return $this;
    }

    public function getArmorClass(): ?string
    {
        return $this->armor_class;
    }

    public function setArmorClass(?string $armor_class): self
    {
        $this->armor_class = $armor_class;

        return $this;
    }

    public function getType(): ?DndEquipmentType
    {
        return $this->type;
    }

    public function setType(?DndEquipmentType $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getSubtype(): ?DndEquipmentSubtype
    {
        return $this->subtype;
    }

    public function setSubtype(?DndEquipmentSubtype $subtype): self
    {
        $this->subtype = $subtype;

        return $this;
    }

    public function getProperties(): ?string
    {
        return $this->properties;
    }

    public function setProperties(?string $properties): self
    {
        $this->properties = $properties;

        return $this;
    }

    public function getStrength(): ?int
    {
        return $this->strength;
    }

    public function setStrength(?int $strength): self
    {
        $this->strength = $strength;

        return $this;
    }

    public function getStealth(): ?string
    {
        return $this->stealth;
    }

    public function setStealth(?string $stealth): self
    {
        $this->stealth = $stealth;

        return $this;
    }

    public function getImagePath(): ?string
    {
        return 'build/images/dnd/' . $this->getImage();
    }
}

src/Entity/DndEquipmentType.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DndEquipmentTypeRepository")
 */
class DndEquipmentType
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\DndEquipment", mappedBy="type")
     */
    private $equipments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\DndEquipmentSubtype", mappedBy="type")
     */
    private $subtypes;

    public function __construct()
    {
        $this->equipments = new ArrayCollection();
        $this->subtypes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|DndEquipment[]
     */
    public function getEquipments(): Collection
    {
        return $this->equipments;
    }

    public function addEquipment(DndEquipment $equipment): self
    {
        if (!$this->equipments->contains($equipment)) {
            $this->equipments[] = $equipment;
            $equipment->setType($this);
        }

        return $this;
    }

    public function removeEquipment(DndEquipment $equipment): self
    {
        if ($this->equipments->contains($equipment)) {
            $this->equipments->removeElement($equipment);
            // set the owning side to null (unless already changed)
            if ($equipment->getType() === $this) {
                $equipment->setType(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|DndEquipmentSubtype[]
     */
    public function getSubtypes(): Collection
    {
        return $this->subtypes;
    }

    public function addSubtype(DndEquipmentSubtype $subtype): self
    {
        if (!$this->subtypes->contains($subtype)) {
            $this->subtypes[] = $subtype;
            $subtype->setType($this);
        }

        return $this;
    }

    public function removeSubtype(DndEquipmentSubtype $subtype): self
    {
        if ($this->subtypes->contains($subtype)) {
            $this->subtypes->removeElement($subtype);
            // set the owning side to null (unless already changed)
            if ($subtype->getType() === $this) {
                $subtype->setType(null);
            }
        }

        return $this;
    }
}

src/Controller/DndEquipmentController.php
<?php

namespace App\Controller;

use App\Repository\DndEquipmentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class DndEquipmentController extends AbstractController
{
    /**
     * @Route("/dnd/equipment", name="dnd_equipment")
     */
    public function index(DndEquipmentRepository $repository, Request $request)
    {
        $q = $request->query->get('q');
        $equipments = $repository->findAllWithSearch($q);

        return $this->render('dnd_equipment/index3.html.twig', [
            'title'      => 'All DnD equipment',
            'equipments'      => $equipments,
        ]);
    }
}

templates/dnd_equipment/_table_part.html.twig
<td>{% if equipment.cost %}{{ equipment.cost|money }}{% else %}–{% endif %}</td>
<td title="{{ equipment.weight|kg }}">
    {% if equipment.weight %}{{ equipment.weight|lb }}{% else %}–{% endif %}
</td>
<td>
    {{ equipment.properties }}
    {% if equipment.type.name == 'Weapons' and not equipment.properties %}–{% endif %}
</td>
<td>{{ equipment.damage }}</td>
<td>{{ equipment.damageType }}</td>
<td>{{ equipment.armorClass }}</td>
<td>
    {{ equipment.strength }}
    {% if equipment.type.name == 'Armor' and not equipment.strength %}–{% endif %}
</td>
<td>
    {{ equipment.stealth }}
    {% if equipment.type.name == 'Armor' and not equipment.stealth %}–{% endif %}
</td>

templates/dnd_equipment/index.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-2">

            <form>
                <div class="input-group input-group-sm mb-3">
                    <input  type="text"
                            name="q"
                            class="form-control"
                            placeholder="Search..."
                            value="{{ app.request.query.get('q') }}"
                    >
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-outline-secondary">
                            <span class="fa fa-search"></span>
                        </button>
                    </div>
                </div>
            </form>

        </div>
    </div>

    <div class="row">
        <div class="col">

            <table class="table table-sm">
                <thead>
                <tr class="table-primary">
                    <th colspan="2">Name</th>
                    <th>Cost</th>
                    <th>Weight</th>
                    <th>Properties</th>
                    <th>Damage</th>
                    <th>Damage Type</th>
                    <th>Armor Class</th>
                    <th>Min strength</th>
                    <th>Stealth</th>
                    <th>Carrying capacity</th>
                    <th>Speed</th>
                </tr>
                </thead>
                <tbody>
                {# @var type \App\Entity\DndEquipmentType #}
                {# @var subtype \App\Entity\DndEquipmentSubtype #}
                {# @var equipment \App\Entity\DndEquipment #}
                {% for type in types %}
                    <tr class="table-secondary">
                        <th colspan="13">{{ type.name|trans({}, 'dnd') }}</th>
                    </tr>
                    {% for equipment in type.equipments %}
                        {% if equipment.subtype is null %}
                            <tr>
                                <td colspan="2">
                                    {% if equipment.image %}
                                        <span class="image-popover" data-toggle="image-popover" data-content="<img src='{{ asset(equipment.imagePath) }}' class='img-fluid' alt='{{ equipment.name }}'>">{{ equipment.name|trans({}, 'dnd') }}</span>
                                    {% else %}
                                        {{ equipment.name }}
                                    {% endif %}
                                </td>
                                {% include 'dnd_equipment/_table_part.html.twig' %}
                            </tr>
                        {% endif %}
                    {% endfor %}
                    {% for subtype in type.subtypes %}
                        <tr class="">
                            <th colspan="13">{{ subtype.name }}</th>
                        </tr>
                        {% for equipment in subtype.equipments %}
                            <tr>
                                <td></td>
                                <td>
                                    {% if equipment.image %}
                                        <span class="image-popover" data-toggle="image-popover" data-content="<img src='{{ asset(equipment.imagePath) }}' class='img-fluid' alt='{{ equipment.name }}'>">{{ equipment.name }}</span>
                                    {% else %}
                                        {{ equipment.name }}
                                    {% endif %}
                                </td>
                                {% include 'dnd_equipment/_table_part.html.twig' %}
                            </tr>
                        {% endfor %}
                    {% endfor %}
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>

{% endblock %}

templates/dnd_equipment/index2.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-2">

            <form>
                <div class="input-group input-group-sm mb-3">
                    <input  type="text"
                            name="q"
                            class="form-control"
                            placeholder="Search..."
                            value="{{ app.request.query.get('q') }}"
                    >
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-outline-secondary">
                            <span class="fa fa-search"></span>
                        </button>
                    </div>
                </div>
            </form>

        </div>
    </div>

    <div class="row">
        <div class="col">

            <table class="table table-sm">
                <thead>
                <tr class="table-primary">
                    <th>Name</th>
                    <th>Type</th>
                    <th>Subtype</th>
                    <th>Cost</th>
                    <th>Weight</th>
                    <th>Properties</th>
                    <th>Damage</th>
                    <th>Damage Type</th>
                    <th>Armor Class</th>
                    <th>Min strength</th>
                    <th>Stealth</th>
                </tr>
                </thead>
                <tbody>
                {# @var type \App\Entity\DndEquipmentType #}
                {# @var subtype \App\Entity\DndEquipmentSubtype #}
                {# @var equipment \App\Entity\DndEquipment #}
                {% for equipment in equipments %}
                    <tr>
                        <td>
                            {% if equipment.image %}
                                <span class="image-popover" data-toggle="image-popover" data-content="<img src='{{ asset(equipment.imagePath) }}' class='img-fluid' alt='{{ equipment.name }}'>">{{ equipment.name|trans({}, 'dnd') }}</span>
                            {% else %}
                                {{ equipment.name }}
                            {% endif %}
                        </td>
                        <td>{{ equipment.type.name }}</td>
                        <td>{% if (equipment.subtype) %}{{ equipment.subtype.name }}{% else %}–{% endif %}</td>
                        {% include 'dnd_equipment/_table_part.html.twig' %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>

{% endblock %}

templates/dnd_equipment/index3.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block body %}
{# @var type \App\Entity\DndEquipmentType #}
{# @var subtype \App\Entity\DndEquipmentSubtype #}
{# @var equipment \App\Entity\DndEquipment #}
    <div class="row">
        <div class="col-2">

            <form>
                <div class="input-group input-group-sm mb-3">
                    <input  type="text"
                            name="q"
                            class="form-control"
                            placeholder="Search..."
                            value="{{ app.request.query.get('q') }}"
                    >
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-outline-secondary">
                            <span class="fa fa-search"></span>
                        </button>
                    </div>
                </div>
            </form>

        </div>
    </div>

    <div class="row">
        <div class="col">

            <table class="table table-sm">
                <thead>
                <tr class="table-primary">
                    <th>Name</th>
                    <th>Type</th>
                    <th>Subtype</th>
                    <th>Cost</th>
                    <th>Weight</th>
                    <th>Properties</th>
                    <th>Damage</th>
                    <th>Damage Type</th>
                    <th>Armor Class</th>
                    <th>Min strength</th>
                    <th>Stealth</th>
                </tr>
                </thead>
                <tbody>

                {% for equipment in equipments %}
                    <tr>
                        <td>
                            {% if equipment.image %}
                                <span class="image-popover" data-toggle="image-popover" data-content="<img src='{{ asset(equipment.imagePath) }}' class='img-fluid' alt='{{ equipment.name }}'>">{{ equipment.name|trans({}, 'dnd') }}</span>
                            {% else %}
                                {{ equipment.name }}
                            {% endif %}
                        </td>
                        <td>{{ equipment.type.name }}</td>
                        <td>{% if (equipment.subtype) %}{{ equipment.subtype.name }}{% else %}–{% endif %}</td>
                        <td>{% if equipment.cost %}{{ equipment.cost|money }}{% else %}–{% endif %}</td>
                        <td title="{{ equipment.weight|kg }}">
                            {% if equipment.weight %}{{ equipment.weight|lb }}{% else %}–{% endif %}
                        </td>
                        <td>
                            {{ equipment.properties }}
                            {% if equipment.type.name == 'Weapons' and not equipment.properties %}–{% endif %}
                        </td>
                        <td>{{ equipment.damage }}</td>
                        <td>{{ equipment.damageType }}</td>
                        <td>{{ equipment.armorClass }}</td>
                        <td>
                            {{ equipment.strength }}
                            {% if equipment.type.name == 'Armor' and not equipment.strength %}–{% endif %}
                        </td>
                        <td>
                            {{ equipment.stealth }}
                            {% if equipment.type.name == 'Armor' and not equipment.stealth %}–{% endif %}
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="11" class="text-center">{{ 'No equipment found'|trans }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>

{% endblock %}