src/Entity/DndCharacter.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DndCharacterRepository")
 */
class DndCharacter
{
    const STATUS_ACTIVE   = 'active';
    const STATUS_INACTIVE = 'inactive';

    const ALLOWED_STATUSES = [
        self::STATUS_ACTIVE,
        self::STATUS_INACTIVE,
    ];

    const LANGUAGE_COMMON      = 'common';
    const LANGUAGE_DWARVISH    = 'dwarvish';
    const LANGUAGE_ELVISH      = 'elvish';
    const LANGUAGE_GIANT       = 'giant';
    const LANGUAGE_GNOMISH     = 'gnomish';
    const LANGUAGE_GOBLIN      = 'goblin';
    const LANGUAGE_HALFLING    = 'halfling';
    const LANGUAGE_ORC         = 'orc';
    const LANGUAGE_ABYSSAL     = 'abyssal';
    const LANGUAGE_CELESTIAL   = 'celestial';
    const LANGUAGE_DRACONIC    = 'draconic';
    const LANGUAGE_DEEP_SPEECH = 'deep speech';
    const LANGUAGE_INFERNAL    = 'infernal';
    const LANGUAGE_PRIMORDIAL  = 'primordial';
    const LANGUAGE_SYLVAN      = 'sylvan';
    const LANGUAGE_UNDERCOMMON = 'undercommon';

    const ALLOWED_LANGUAGES = [
        self::LANGUAGE_COMMON,
        self::LANGUAGE_DWARVISH,
        self::LANGUAGE_ELVISH,
        self::LANGUAGE_GIANT,
        self::LANGUAGE_GNOMISH,
        self::LANGUAGE_GOBLIN,
        self::LANGUAGE_HALFLING,
        self::LANGUAGE_ORC,
        self::LANGUAGE_ABYSSAL,
        self::LANGUAGE_CELESTIAL,
        self::LANGUAGE_DRACONIC,
        self::LANGUAGE_DEEP_SPEECH,
        self::LANGUAGE_INFERNAL,
        self::LANGUAGE_PRIMORDIAL,
        self::LANGUAGE_SYLVAN,
        self::LANGUAGE_UNDERCOMMON,
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="dndCharacters")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\DndClass", inversedBy="characters")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank
     */
    private $class;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\DndRace", inversedBy="characters")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank
     */
    private $race;

    /**
     * @ORM\Column(type="string", length=30)
     * @Assert\NotBlank
     * @Assert\Regex("/^\w+$/")
     * @Assert\Length(min = 2, max = 30)
     */
    private $name;

    /**
     * @ORM\Column(type="integer", options={"default" = 1})
     * @Assert\NotBlank
     * @Assert\Range(min = 0, max = 20)
     */
    private $level = 1;

    /**
     * @ORM\Column(type="integer", options={"default" = 0})
     * @Assert\NotBlank
     * @Assert\GreaterThanOrEqual(value = 0)
     */
    private $experience_points = 0;

    /**
     * @ORM\Column(type="integer", options={"default" = 0})
     * @Assert\NotBlank
     */
    private $money = 0;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     * @Assert\Range(min = 1, max = 30)
     */
    private $strength;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     * @Assert\Range(min = 1, max = 30)
     */
    private $dexterity;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     * @Assert\Range(min = 1, max = 30)
     */
    private $constitution;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     * @Assert\Range(min = 1, max = 30)
     */
    private $intelligence;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     * @Assert\Range(min = 1, max = 30)
     */
    private $wisdom;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     * @Assert\Range(min = 1, max = 30)
     */
    private $charisma;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     * @Assert\Range(min = 1)
     */
    private $armor_class;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $languages = [];

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status = self::STATUS_ACTIVE;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getClass(): ?DndClass
    {
        return $this->class;
    }

    public function setClass(?DndClass $class): self
    {
        $this->class = $class;

        return $this;
    }

    public function getRace(): ?DndRace
    {
        return $this->race;
    }

    public function setRace(?DndRace $race): self
    {
        $this->race = $race;

        return $this;
    }

    public function getStrength(): ?int
    {
        return $this->strength;
    }

    public function setStrength(?int $strength): self
    {
        $this->strength = $strength;

        return $this;
    }

    public function getDexterity(): ?int
    {
        return $this->dexterity;
    }

    public function setDexterity(?int $dexterity): self
    {
        $this->dexterity = $dexterity;

        return $this;
    }

    public function getConstitution(): ?int
    {
        return $this->constitution;
    }

    public function setConstitution(?int $constitution): self
    {
        $this->constitution = $constitution;

        return $this;
    }

    public function getIntelligence(): ?int
    {
        return $this->intelligence;
    }

    public function setIntelligence(?int $intelligence): self
    {
        $this->intelligence = $intelligence;

        return $this;
    }

    public function getWisdom(): ?int
    {
        return $this->wisdom;
    }

    public function setWisdom(?int $wisdom): self
    {
        $this->wisdom = $wisdom;

        return $this;
    }

    public function getCharisma(): ?int
    {
        return $this->charisma;
    }

    public function setCharisma(?int $charisma): self
    {
        $this->charisma = $charisma;

        return $this;
    }

    public function getMoney(): ?int
    {
        return $this->money;
    }

    public function setMoney(?int $money): self
    {
        $this->money = $money;

        return $this;
    }

    public function getArmorClass(): ?int
    {
        return $this->armor_class;
    }

    public function setArmorClass(?int $armor_class): self
    {
        $this->armor_class = $armor_class;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getLevel(): ?int
    {
        return $this->level;
    }

    public function setLevel(?int $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getExperiencePoints(): ?int
    {
        return $this->experience_points;
    }

    public function setExperiencePoints(?int $experience_points): self
    {
        $this->experience_points = $experience_points;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        if (!in_array($status,self::ALLOWED_STATUSES)) {
            throw new \InvalidArgumentException("Invalid Dnd Character status");
        }

        $this->status = $status;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getModifier($abilityScore): int
    {
        return floor(($abilityScore - 10) / 2);
    }

    public function getLanguages(): ?array
    {
        return $this->languages;
    }

    public function setLanguages(?array $languages): self
    {
        foreach ($languages as $language) {
            if (!in_array($language, self::ALLOWED_LANGUAGES)) {
                throw new \InvalidArgumentException("Invalid language");
            }
        }

        $this->languages = $languages;

        return $this;
    }
}

src/Form/DndCharacterType.php
<?php

namespace App\Form;

use App\Entity\DndCharacter;
use App\Entity\DndClass;
use App\Entity\DndRace;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DndCharacterType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name',TextType::class, [
                'label'  => 'Name',
                'help' => 'Only letters, digits, and underscore.',
                'attr' => ['autofocus' => true],
            ])
            ->add('class', EntityType::class, [
                'class'       => DndClass::class,
                'placeholder' => 'Choose a class'
            ])
            ->add('race', EntityType::class, [
                'class' => DndRace::class,
                'placeholder' => 'Choose a race'
            ])
            ->add('level',TextType::class)
            ->add('experience_points',TextType::class)
            ->add('money',TextType::class)
            ->add('strength',TextType::class)
            ->add('dexterity',TextType::class)
            ->add('constitution',TextType::class)
            ->add('intelligence',TextType::class)
            ->add('wisdom',TextType::class)
            ->add('charisma',TextType::class)
            ->add('armor_class',TextType::class)
            ->add('description', TextareaType::class)

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => DndCharacter::class,
        ]);
    }
}

src/Controller/DndCharacterController.php
<?php

namespace App\Controller;

use App\Entity\DndCharacter;
use App\Form\DndCharacterType;
use App\Repository\DndCharacterRepository;
use Psr\Log\LoggerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * @Route("/dnd/character")
 * @IsGranted("ROLE_USER")
 */
class DndCharacterController extends BaseController
{
    /**
     * @Route("/", name="dnd_character_index", methods="GET")
     */
    public function index(DndCharacterRepository $dndCharacterRepository): Response
    {
        return $this->render('dnd_character/index2.html.twig', [
            'dnd_characters' => $dndCharacterRepository->findAll()
        ]);
    }

    /**
     * @Route("/new", name="dnd_character_new", methods="GET|POST")
     */
    public function new(Request $request, LoggerInterface $logger, TranslatorInterface $translator): Response
    {
        $dndCharacter = new DndCharacter();
        $form = $this->createForm(DndCharacterType::class, $dndCharacter);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $dndCharacter->setUser($this->getUser());
            $em = $this->getDoctrine()->getManager();
            $em->persist($dndCharacter);
            $em->flush();

            $logger->info('D&D character created', [
                'user_id'      => $this->getUser()->getId(),
                'character_id' => $dndCharacter->getId(),
            ]);

            $this->addFlash(
                'success',
                $translator->trans('Character created')
            );

            return $this->redirectToRoute('dnd_character_show', [
                'id' => $dndCharacter->getId()
            ]);
        }

        return $this->render('dnd_character/new.html.twig', [
            'dnd_character' => $dndCharacter,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="dnd_character_show", methods="GET")
     */
    public function show(DndCharacter $dndCharacter): Response
    {
        return $this->render('dnd_character/show.html.twig', [
            'dnd_character' => $dndCharacter
        ]);
    }

    /**
     * @Route("/{id}/edit", name="dnd_character_edit", methods="GET|POST")
     */
    public function edit(
        Request $request,
        DndCharacter $dndCharacter,
        LoggerInterface $logger,
        TranslatorInterface $translator
    ): Response
    {
        $form = $this->createForm(DndCharacterType::class, $dndCharacter);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            $logger->info('D&D character edited', [
                'user_id'      => $this->getUser()->getId(),
                'character_id' => $dndCharacter->getId(),
            ]);

            $this->addFlash(
                'success',
                $translator->trans('Character edited')
            );

            return $this->redirectToRoute('dnd_character_show', [
                'id' => $dndCharacter->getId()
            ]);
        }

        return $this->render('dnd_character/edit.html.twig', [
            'dnd_character' => $dndCharacter,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="dnd_character_delete", methods="DELETE")
     */
    public function delete(
        Request $request,
        DndCharacter $dndCharacter,
        LoggerInterface $logger,
        TranslatorInterface $translator
    ): Response
    {
        if ($this->isCsrfTokenValid('delete' . $dndCharacter->getId(), $request->request->get('_token'))) {
            $id = $dndCharacter->getId();
            $em = $this->getDoctrine()->getManager();
            $em->remove($dndCharacter);
            $em->flush();
            
            $logger->info('D&D character deleted', [
                'user_id'      => $this->getUser()->getId(),
                'character_id' => $id,
            ]);

            $this->addFlash(
                'success',
                $translator->trans('Character deleted')
            );
        }

        return $this->redirectToRoute('dnd_character_index');
    }
}

templates/dnd_character/_delete_form.html.twig
<form method="post" action="{{ path('dnd_character_delete', {'id': dnd_character.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ dnd_character.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/dnd_character/_form.html.twig
{% form_theme form 'form/errors.html.twig' %}

{{ form_start(form) }}
    {{ form_errors(form) }}

    <div class="form-row">
        <div class="form-group col-xs-12 col-sm-4">
            {{ form_label(form.name) }}
            {{ form_widget(form.name, {'attr': {'class': 'form-control-sm'}}) }}
            {{ form_help(form.name) }}
        </div>
        <div class="form-group col-xs-12 col-sm-4">
            {{ form_label(form.class) }}
            {{ form_widget(form.class, {'attr': {'class': 'form-control-sm'}}) }}
            {{ form_help(form.class) }}
        </div>
        <div class="form-group col-xs-12 col-sm-4">
            {{ form_label(form.race) }}
            {{ form_widget(form.race, {'attr': {'class': 'form-control-sm'}}) }}
            {{ form_help(form.race) }}
        </div>
    </div>

<div class="form-row">
    <div class="form-group col-xs-12 col-sm-4">
        {{ form_label(form.level) }}
        {{ form_widget(form.level, {'attr': {'class': 'form-control-sm'}}) }}
        {{ form_help(form.level) }}
    </div>
    <div class="form-group col-xs-12 col-sm-4">
        {{ form_label(form.experience_points) }}
        {{ form_widget(form.experience_points, {'attr': {'class': 'form-control-sm'}}) }}
        {{ form_help(form.experience_points) }}
    </div>
    <div class="form-group col-xs-12 col-sm-4">
        {{ form_label(form.money) }}
        {{ form_widget(form.money, {'attr': {'class': 'form-control-sm'}}) }}
        {{ form_help(form.money) }}
    </div>
</div>

<div class="form-row">
    <div class="form-group col-xs-6 col-sm-4 col-md-2">
        {{ form_label(form.strength) }}
        {{ form_widget(form.strength, {'attr': {'class': 'form-control-sm'}}) }}
        {{ form_help(form.strength) }}
    </div>
    <div class="form-group col-xs-12 col-sm-4 col-md-2">
        {{ form_label(form.dexterity) }}
        {{ form_widget(form.dexterity, {'attr': {'class': 'form-control-sm'}}) }}
        {{ form_help(form.dexterity) }}
    </div>
    <div class="form-group col-xs-12 col-sm-4 col-md-2">
        {{ form_label(form.constitution) }}
        {{ form_widget(form.constitution, {'attr': {'class': 'form-control-sm'}}) }}
        {{ form_help(form.constitution) }}
    </div>
    <div class="form-group col-xs-12 col-sm-4 col-md-2">
        {{ form_label(form.intelligence) }}
        {{ form_widget(form.intelligence, {'attr': {'class': 'form-control-sm'}}) }}
        {{ form_help(form.intelligence) }}
    </div>
    <div class="form-group col-xs-12 col-sm-4 col-md-2">
        {{ form_label(form.wisdom) }}
        {{ form_widget(form.wisdom, {'attr': {'class': 'form-control-sm'}}) }}
        {{ form_help(form.wisdom) }}
    </div>
    <div class="form-group col-xs-12 col-sm-4 col-md-2">
        {{ form_label(form.charisma) }}
        {{ form_widget(form.charisma, {'attr': {'class': 'form-control-sm'}}) }}
        {{ form_help(form.charisma) }}
    </div>
    <div class="form-group col-xs-12 col-sm-4 col-md-2">
        {{ form_label(form.armor_class) }}
        {{ form_widget(form.armor_class, {'attr': {'class': 'form-control-sm'}}) }}
        {{ form_help(form.armor_class) }}
    </div>
</div>

    <div class="form-group text-center">
        <button type="submit" class="btn btn-block btn-primary text-center" formnovalidate>{{ button_label|default('Save') }}</button>
    </div>
{{ form_end(form) }}

templates/dnd_character/edit.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}{{ dnd_character.name }} – edit D&D character{% endblock %}

{% block body %}

    <div class="row">
        <div class="col-md-8 offset-md-2 col-lg-6 offset-lg-3">
            <h1 class="d-inline-block">Edit D&D character</h1>
            <a class="btn btn-sm btn-primary float-right" href="{{ path('dnd_character_index') }}">
                <i class="fas fa-arrow-left"></i> Back to list
            </a>
            {{ include('dnd_character/_delete_form.html.twig') }}
            <hr>
        </div>
        <div class="col-md-8 offset-md-2 col-lg-6 offset-lg-3">
            {{ include('dnd_character/_form.html.twig', {'button_label': 'Update'}) }}
        </div>
    </div>

{% endblock %}

templates/dnd_character/index.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}D&D character list{% endblock %}

{% block body %}
    <h1>Your D&D characters</h1>

    <table id="data-table" class="table table-sm table-responsive">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Class</th>
                <th>Race</th>
                <th>Level</th>
                <th title="Experience points">XP</th>
                <th>Money</th>
                <th title="Strength">Str</th>
                <th title="Dexterity">Dex</th>
                <th title="Constitution">Con</th>
                <th title="Intelligence">Int</th>
                <th title="Wisdom">Wis</th>
                <th title="Charisma">Cha</th>
                <th title="Armor Class">AC</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for dnd_character in dnd_characters %}
            <tr>
                <td>{{ dnd_character.id }}</td>
                <td>{{ dnd_character.name }}</td>
                <td>{{ dnd_character.class.name }}</td>
                <td>{{ dnd_character.race.name }}</td>
                <td>{{ dnd_character.level }}</td>
                <td>{{ dnd_character.experiencePoints }}</td>
                <td><nobr>{{ dnd_character.money|money }}</nobr></td>
                <td>{{ dnd_character.strength }}</td>
                <td>{{ dnd_character.dexterity }}</td>
                <td>{{ dnd_character.constitution }}</td>
                <td>{{ dnd_character.intelligence }}</td>
                <td>{{ dnd_character.wisdom }}</td>
                <td>{{ dnd_character.charisma }}</td>
                <td>{{ dnd_character.armorClass }}</td>
                <td>
                    <a class="btn btn-sm btn-primary" href="{{ path('dnd_character_show', {'id': dnd_character.id}) }}">
                        <i class="fas fa-eye"></i> <span class="hidden-xs">Show</span>
                    </a>
                    <a class="btn btn-sm btn-primary" href="{{ path('dnd_character_edit', {'id': dnd_character.id}) }}">
                        <i class="fas fa-edit"></i> Edit
                    </a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="13">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-sm btn-primary" href="{{ path('dnd_character_new') }}"><i class="fas fa-plus-square"></i>  Create new</a>
{% endblock %}

templates/dnd_character/index2.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}D&D character list{% endblock %}

{% block body %}

    <style>
        .badge {
            padding: 0.3rem 0.5rem;
        }
        .badge-ability {
            display: inline-block;
            width: 50px;
        }
        .badge-modifier {
            display: inline-block;
            width: 25px;
        }
    </style>

    <div class="row">
        <div class="col">
            <a class="btn btn-sm btn-primary" href="{{ path('dnd_character_new') }}"><i class="fas fa-plus-square"></i>  Create new</a>
            <h1>Your D&D characters</h1>
        </div>
    </div>

    <div class="row">
        {% for character in dnd_characters %}
        <div class="col-xs-12 col-sm-6 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
            <div class="card border-primary mb-3">
                <div class="card-header">
                    <span class="h5" title="{{ character.id }}">{{ character.name }}</span>
                    <span class="badge badge-dark float-right">{{ character.level }} lvl</span>
                    <span class="badge badge-primary float-right">{{ character.experiencePoints }} XP</span>
                    <br>
                    <span class="h6">{{ character.race.name }} {{ character.class.name }}</span>
                    <span class="h6">{{ character.money|money }}</span>
                    <span class="float-right"><i class="fa fa-shield-alt"></i> {{ character.armorClass }}</span>
                </div>
                <div class="card-body">
                    {% macro abilities(ability, name, modifier) %}
                        <span class="badge badge-primary badge-ability">{{ ability }} {{ name }}</span>
                        <span class="badge badge-primary badge-modifier">{{ modifier }}</span>
                    {% endmacro %}

                    {% import _self as this %}

                    {{ this.abilities(character.strength, 'str', character.modifier(character.strength)) }}
                    <br>
                    {{ this.abilities(character.dexterity, 'dex', character.modifier(character.dexterity)) }}
                    <br>
                    {{ this.abilities(character.constitution, 'con', character.modifier(character.constitution)) }}
                    <br>
                    {{ this.abilities(character.intelligence, 'int', character.modifier(character.intelligence)) }}
                    <br>
                    {{ this.abilities(character.wisdom, 'wis', character.modifier(character.wisdom)) }}
                    <br>
                    {{ this.abilities(character.charisma, 'cha', character.modifier(character.charisma)) }}
                    <br>






                    <h4 class="card-title">Card title</h4>
                    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="card-link">Card link</a>
                    <a href="#" class="card-link">Another link</a>
                </div>
                <div class="card-footer text-muted">
                    <a class="btn btn-sm btn-primary" href="{{ path('dnd_character_show', {'id': character.id}) }}">
                        <i class="fas fa-eye"></i> <span class="hidden-xs">Show</span>
                    </a>
                    <a class="btn btn-sm btn-primary" href="{{ path('dnd_character_edit', {'id': character.id}) }}">
                        <i class="fas fa-edit"></i> Edit
                    </a>
                </div>
            </div>
        </div>
        {% else %}
            <tr>
                <td colspan="13">No characters found</td>
            </tr>
        {% endfor %}
    </div>

{% endblock %}

templates/dnd_character/new.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}Create D&D character{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-8 offset-md-2 col-lg-6 offset-lg-3">
            <h1>Create D&D character</h1>
            <hr>

            {{ include('dnd_character/_form.html.twig') }}
        </div>
    </div>
{% endblock %}

templates/dnd_character/show.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}D&D character{% endblock %}

{% block body %}

    <style>
        .badge-ability {
            padding: 0.3rem 0.5rem;
            display: inline-block;
            width: 50px;
        }
        .badge-modifier {
            padding: 0.3rem 0.5rem;
            display: inline-block;
            width: 25px;
        }
    </style>

    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
            <h1>D&D character</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
            <div class="card border-primary mb-3">
                <div class="card-header">
                    <span class="h5" title="{{ dnd_character.id }}">{{ dnd_character.name }}</span>
                    <span class="badge badge-dark float-right">{{ dnd_character.level }} lvl</span>
                    <span class="badge badge-primary float-right">{{ dnd_character.experiencePoints }} XP</span>
                    <br>
                    <span class="h6">{{ dnd_character.race.name }} {{ dnd_character.class.name }}</span>
                    <span class="h6 float-right">{{ dnd_character.money|money }}</span>
                    {#<span class="float-right"><i class="fa fa-shield-alt"></i> {{ dnd_character.armorClass }}</span>#}
                </div>
                <div class="card-body">
                    {% macro abilities(ability, name, modifier) %}
                        <span class="badge badge-primary badge-ability">{{ ability }} {{ name }}</span>
                        <span class="badge badge-primary badge-modifier">{{ modifier }}</span>
                    {% endmacro %}

                    {% import _self as this %}

                    {{ this.abilities(dnd_character.strength, 'str', dnd_character.modifier(dnd_character.strength)) }}
                    <br>
                    {{ this.abilities(dnd_character.dexterity, 'dex', dnd_character.modifier(dnd_character.dexterity)) }}
                    <br>
                    {{ this.abilities(dnd_character.constitution, 'con', dnd_character.modifier(dnd_character.constitution)) }}
                    <br>
                    {{ this.abilities(dnd_character.intelligence, 'int', dnd_character.modifier(dnd_character.intelligence)) }}
                    <br>
                    {{ this.abilities(dnd_character.wisdom, 'wis', dnd_character.modifier(dnd_character.wisdom)) }}
                    <br>
                    {{ this.abilities(dnd_character.charisma, 'cha', dnd_character.modifier(dnd_character.charisma)) }}
                    <br>



                    <h4 class="card-title">Card title</h4>
                    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="card-link">Card link</a>
                    <a href="#" class="card-link">Another link</a>
                </div>
                <div class="card-footer text-muted">
                    <a class="btn btn-sm btn-primary" href="{{ path('dnd_character_show', {'id': dnd_character.id}) }}">
                        <i class="fas fa-eye"></i> <span class="hidden-xs">Show</span>
                    </a>
                    <a class="btn btn-sm btn-primary" href="{{ path('dnd_character_edit', {'id': dnd_character.id}) }}">
                        <i class="fas fa-edit"></i> Edit
                    </a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}